version: '3.4'

services:
  transit_measurement_video_service:
    image: transit_measurement_video_service
    container_name: transit_measurement_video_service
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - FAST_API_KEY=${FAST_API_KEY}
      - AUTO_RELOAD=${AUTO_RELOAD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile.video
    volumes:
      - ./shared:/app/src/shared
      - ./video-service/src:/app/src
    ports:
      - "81:80"
    depends_on:
      - transit_measurement_service_db
      - transit_measurement_service_queue
  transit_measurement_api_service:
    image: transit_measurement_api_service
    container_name: transit_measurement_api_service
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - FAST_API_KEY=${FAST_API_KEY}
      - AUTO_RELOAD=${AUTO_RELOAD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - ./shared:/app/src/shared
      - ./api-service/src:/app/src
    ports:
      - "80:80"
    depends_on:
      - transit_measurement_video_service
  transit_measurement_service_db:
    image: mysql:8.0
    container_name: transit_measurement_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3305:3306'
    expose:
      - '3305'
    volumes:
      - transit_measurement_service_db:/var/lib/mysql
  transit_measurement_service_queue:
    image: redis:7.0.12-alpine
    container_name: transit_measurement_service_queue
    restart: always
    environment:
      REDIS_LOG_LEVEL: ${REDIS_LOG_LEVEL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --loglevel $$REDIS_LOG_LEVEL --requirepass $$REDIS_PASSWORD"
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - transit_measurement_service_queue:/data
volumes:
  transit_measurement_service_db:
  transit_measurement_service_queue: