version: '3.4'

services:
  transit_measurement_video_service:
    image: transit_measurement_video_service
    container_name: transit_measurement_video_service
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - FAST_API_KEY=${FAST_API_KEY}
      - AUTO_RELOAD=${AUTO_RELOAD}
    build:
      context: .
      dockerfile: ./Dockerfile.video
    volumes:
      - ./database:/app/src/database
      - ./video-service/src:/app/src
    ports:
      - "81:80"
    depends_on:
      - transit_measurement_service_db
  transit_measurement_api_service:
    image: transit_measurement_api_service
    container_name: transit_measurement_api_service
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - FAST_API_KEY=${FAST_API_KEY}
      - AUTO_RELOAD=${AUTO_RELOAD}
    build:
      context: .
      dockerfile: ./Dockerfile.api
    volumes:
      - ./database:/app/src/database
      - ./api-service/src:/app/src
    ports:
      - "80:80"
    depends_on:
      - transit_measurement_video_service
transit_measurement_service_db:
    image: mysql:8.0
    container_name: transit_measurement_service_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transit_measurement_service_db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - transit_measurement_service_db:/var/lib/mysql
volumes:
  transit_measurement_service_db: