version: '3.4'

services:
  noble_etl:
    image: transit_measurement_service
    container_name: transit_measurement_service
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - FAST_API_KEY=${FAST_API_KEY}
      - AUTO_RELOAD=${AUTO_RELOAD}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "80:80"
